version: '3.7'

services:
  app:
    build: .
    image: mery/streaming-data:v1
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    command: ["python", "etl_binance_data_streaming.py"]