#ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches-ignore:
      - 'main'
#on:
  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Continuous Integration Build and push opa-api Docker image
      run: |
        docker build -t sokhnamery/opa-api ./API
        docker push sokhnamery/opa-api

    - name: Build and push streaming-data Docker image
      run: |
        docker build -t sokhnamery/streaming-data ./ETL/Streaming
        docker push sokhnamery/streaming-data

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Continuous Deployment to server
      run: |
        docker run --env-file .venv -p 8000:8000 sokhnamery/streaming-data
        docker run --env-file .venv -p 8000:8000 sokhnamery/opa-api
